config/routes.rb
Rails.application.routes.draw do
  
  post 'posts/:id/comments/create' => 'comments#create'
  delete 'comments/:id' => 'comments#destroy'
  
  get 'comments/destroy'

  resources :posts
  root 'post#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :post
end

app/models/daum.rb
class Daum < ApplicationRecord
    has_many :memberships
    has_many :users, through: :memberships
end

app/models/membership.rb
class Membership < ApplicationRecord
    belongs_to :user
    belongs_to :daum
end

app/models/post.rb
class Post < ApplicationRecord
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
    has_many :memberships
    has_many :daums, through: :memberships
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    comment = Comment.new
    comment.content = params[:content]
    comment.post_id = params[:id]
    comment.save
    
    redirect_to :back
  end

  def destroy
    comment = Comment.find(params[:id]) #댓글의 id를 가져오는 
    comment.destroy
    
    redirect_to :back
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

      if @post.save # 
        redirect_to @post, flash: {success: 'Post was successfully created.'}
      else
        render :new
      end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
      if @post.update(post_params)
        redirect_to @post, flash: {success: 'Post was successfully updated.'}
      else
        render :edit
      end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
      redirect_to posts_url, flash: {success: 'Post was successfully destroyed.'}
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :contents, :text)
      # {title: params[:post][:title]m contents: [:post][:contents]} 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.erb
<%= form_tag("/posts/#{post.id}/comments/create") do %>
    
    <%= text_field_tag(:content, nil, class: "form-control", placeholder: "내용을 입력하세요") %>
    <br>
    <%= submit_tag("댓글작성", class: "btn btn-primary")%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DaumCafe</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <% flash.each do |k,v|%>
  
      <div data-spy="scroll" class="alert alert-<%= k%>"><%= v %></div>
    <% end  %>
    <div class="container overflow:auto">
    <%= yield %>
    </div>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for(post, html: {class: 'text-left'}) do |f| %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :contents %>
    <%= f.text_field :contents, class: 'form-control' %>
  </div>

  <div class="field">
    <%= f.label :text %>
    <%= f.text_field :text, class: 'form-control' %>
  </div>
  
  <br>
  <div class="actions text-right">
    <%= f.submit '작성하기', class: 'btn btn-info'  %>
    <%= link_to '뒤로가기', posts_path, class: 'btn btn-warning text-white' %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<h1>Posts</h1>

<ul class="list-group">
  <% @posts.each do |post| %>
  <li class="list-group-item d-flex justify-content-between align-items-center">
    <%= link_to "#{post.title}", post_path(post) %><!-- 경로에 id가 붙는 건 post를 붙여서 -->
    <span class="badge badge-primary badge-pill"><%=post.comments.count%></span>
  </li>
  <% end  %>
</ul>
<br>
<div class="text-right">
<%= link_to 'New Post', new_post_path, class: 'btn btn-primary' %>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

app/views/posts/show.html.erb
<h1>
  <strong>Title:</strong>
  <%= @post.title %>
</h1>
<hr/>

<p>
  <strong>Contents:</strong>
  <%= @post.contents %>
</p>

<p>
  <strong>Text:</strong>
  <%= @post.text %>
</p>

<%= link_to '수정', edit_post_path(@post), class: 'btn btn-warning text-white' %> &nbsp;
<%= link_to '목록', posts_path, class: 'btn btn-info' %>&nbsp;
<%= link_to '삭제', post_path(@post), class: 'btn btn-danger', method: 'DELETE', data: {confirm: "삭제하시겠습니까?"}%>

<br><br>
<!--  댓글 입력 -->
<%= render 'comments/form' ,post: @post %><br>

<!--  댓글 리스트 -->

<table class="table">
  <thead>
    <tr>
      <th scope="col">id</th>
      <th scope="col">Content</th>
      <th scope="col">Button</th>
    </tr>
  </thead>
  <tbody>
  <% @post.comments.each do |comment| %>
    <tr>
      <th scope="row"><%= comment.id %></th>
      <td><%= comment.content %></td>
      <td><%= link_to "삭제", "comments/#{comment.id}", class: 'btn btn-danger', method: "delete" %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/shared/_footer.html.erb
<footer class="footer">
      <div class="container">
        <span class="text-muted">Place sticky footer content here.</span>
      </div>
    </footer>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-xl navbar-dark bg-dark">
      <a class="navbar-brand" href="#">Expand at xl</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample06" aria-controls="navbarsExample06" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExample06">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Link</a>
          </li>
          <li class="nav-item">
            <a class="nav-link disabled" href="#">Disabled</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="https://example.com" id="dropdown06" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
            <div class="dropdown-menu" aria-labelledby="dropdown06">
              <a class="dropdown-item" href="#">Action</a>
              <a class="dropdown-item" href="#">Another action</a>
              <a class="dropdown-item" href="#">Something else here</a>
            </div>
          </li>
        </ul>
        <form class="form-inline my-2 my-md-0">
          <input class="form-control" type="text" placeholder="Search">
        </form>
      </div>
    </nav>